services:
  - type: web
    name: gemini-chat-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    branch: main
    envVars:
      - key: GEMINI_API_KEY
        sync: false
